name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    permissions:
      contents: read
    uses: developer-experience-DevEX-platform/ci-cd-templates/.github/workflows/python-ci.yml@v1.7.0
    secrets: inherit
    with:
      has_integration_tests: true

  release:
    needs: ci
    permissions:
      contents: read
      id-token: write
    uses: developer-experience-DevEX-platform/ci-cd-templates/.github/workflows/container-release.yml@v1.7.0

  deploy-staging:
    name: Deploy to staging
    needs: release
    permissions:
      contents: read
    uses: developer-experience-DevEX-platform/ci-cd-templates/.github/workflows/kubernetes-gitops-cd.yml@v1.7.0
    secrets: inherit
